// Generated by https://quicktype.io

class ActorModel {
  bool? adult;
  int? gender;
  int? id;
  String? known_for_department;
  String? name;
  String? original_name;
  double? popularity;
  String? profile_path;
  int? cast_id;
  String? character;
  String? credit_id;
  int? order;

  ActorModel({
    this.adult,
    this.gender,
    this.id,
    this.known_for_department,
    this.name,
    this.original_name,
    this.popularity,
    this.profile_path,
    this.cast_id,
    this.character,
    this.credit_id,
    this.order,
  });

  factory ActorModel.fromMap(Map<String, dynamic> map) {
    return ActorModel(
      adult: map['adult'],
      gender: map['gender'],
      id: map['id'],
      known_for_department: map['known_for_department'],
      name: map['name'],
      original_name: map['original_name'],
      popularity: map['popularity'],
      profile_path: map['profile_path'] ?? '',
      cast_id: map['cast_id'],
      character: map['character'],
      credit_id: map['credit_id'],
      order: map['order'],
    );
  }
}